// AsciiDoc TOC settings
:toc:
:toc-placement!:
:toc-title:

// GitHub Flavored Asciidoc (GFA). See https://gist.github.com/dcode/0cfbf2699a1fe9b46ff04c41721dda74 for details.
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= terraform-github-repository

image:https://img.shields.io/badge/maintained%20by-mineiros.io-%235849a6.svg[Maintained by Mineiros.io, link="https://www.mineiros.io/ref=repo_terraform-github-repository"]
image:https://img.shields.io/github/tag/meineiros-io/terraform-github-repository.svg?label=latest[GitHub tag (latest Semantic Version), link="https://github.com/mineiros-io/terraform-github-repository/releases"]
image:https://img.shields.io/badge/tf-%3E%3D0.12.9-blue.svg[Terraform Version]

[.lead]
A Terraform module that acts as a wrapper around the Terraform https://www.terraform.io/docs/providers/github/index.html[GitHub provider]
and offers a more convenient and tested way to provision and manage GitHub Repositories within your GitHub organization following best practices.

[NOTE]
====
This module cannot currently be used to manage personal repositories, outside of organizations due to limitations of the Terraform https://www.terraform.io/docs/providers/github/index.html[GitHub provider].
====

[TIP]
====
This Module uses `For, For-Each and Dynamic Nested Blocks` that were introduced in Terraform 0.12.
A common problem in Terraform configurations for versions 0.11 and earlier is dealing with situations where the number
of values or resources is decided by a dynamic expression rather than a fixed count.

You can now dynamically add and remove items from and to Lists without
the necessity to render the whole list of resources again. Terraform will only add and remove the items you want it to.
====

== Table of Contents
toc::[]

== Requirements
This module requires version `~> 0.12.9` of Terraform.
This module requires version `~> 2.2` of the GitHub provider

== Features
This module uses https://github.com/terraform-providers/terraform-provider-github/releases[Terraform GitHub provider v2.2.1] that supports the following resources:

* Repositories
* Branch Protections
* Teams & Collaborators
* Issue Labels
* Deployment Keys
* Projects
* Webhooks

== Examples
For a complete example please see link:/examples[examples] directory.

== Limitations
- Currently the https://www.terraform.io/docs/providers/github/index.html[GitHub Provider] doesn't support to rename repositories.
- Currently the https://www.terraform.io/docs/providers/github/index.html[GitHub Provider] doesn't support to manage personal repositories, outside of organizations.
